-- noinspection SqlDialectInspectionForFile
-- noinspection SqlNoDataSourceInspectionForFile

INSERT INTO master_item(item_code, item_name, item_type, uom)
VALUES  ('BB001', 'Bir Bintang Barel 30L', 'BEVERAGE', 'LTR'),
        ('BB002', 'Bir Bintang Botol 620ML', 'BEVERAGE', 'BTL'),
        ('BB003', 'Bir Bintang Can' 'BEVERAGE', 'CAN'),
        ('BB004', 'Corona 330ML' 'BEVERAGE', 'BTL'),
        ('BB005', 'Guiness Stout Botol 330ML' 'BEVERAGE', 'BTL'),
        ('BB006', 'Heineken 330ML/BTL' 'BEVERAGE', 'BTL'),
        ('BB007', 'Heineken Barel 20L/BAREL' 'BEVERAGE', 'LTR'),
        ('BB008', 'Heineken Botol Kosong' 'BEVERAGE', 'BTL'),
        ('BB009', 'Konig Ludwig 500ML/BTL' 'BEVERAGE', 'BTL'),
        ('BRW001', 'Barone Ricasoli Chianti 750ML', 'BEVERAGE', 'BTL'),
        ('BRW002', 'Cabernet Sauvignon, 30 MILE 750ML', 'BEVERAGE', 'BTL'),
        ('BRW003', 'Calvet Reserve Bourdeaux Merlot Cs', 'BEVERAGE', 'BTL'),
        ('BRW004', 'Saint Roman Chanteau, Bordeaux 750ML', 'BEVERAGE', 'BTL'),
        ('BRW005', 'Chapoutier, La Ciboise Luberon Rouge 750M', 'BEVERAGE', 'BTL'),
        ('BRW006', 'Cotes Du Rhone', 'BEVERAGE', 'BTL'),
        ('BRW007', 'Cuvee Special Red', 'BEVERAGE', 'BTL'),
        ('BRW008', 'E. Guigal Chateauneuf Du Pape 750ML', 'BEVERAGE', 'BTL'),
        ('BRW009', 'Everyday Red NV, Delicato California 750ML', 'BEVERAGE', 'BTL'),
        ('BRW010', 'Fortant De France Terroir Littoral Merlo', 'BEVERAGE', 'BTL'),
        ('BRW011', 'Frontera Merlot 2013 , Chile Red 750ML', 'BEVERAGE', 'BTL'),
        ('BRW012', 'Hardys Shiraz Carbenet Red', 'BEVERAGE', 'BTL'),
        ('BRW013', 'Hatten Red Wine 2000ML', 'BEVERAGE', 'BTL'),
        ('BRW014', 'Jacobs Creek Shiraz Carbenet 750ML', 'BEVERAGE', 'BTL'),
        ('BRW015', 'Lindeman 45 Carbenet Sauvignon', 'BEVERAGE', 'BTL'),
        ('BRW016', 'Lindeman 50 Shiraz 750ML', 'BEVERAGE', 'BTL'),
        ('BRW017', 'Paul Jaboulet Cotes Du Rhone 750ML', 'BEVERAGE', 'BTL'),
        ('BRW018', 'Plaga 1500ML', 'BEVERAGE', 'BTL'),
        ('BRW019', 'Plaga Red Wine 3000ML', 'BEVERAGE', 'BTL'),
        ('BRW020', 'Roger Sabon Cotes Du Rhone 750ML', 'BEVERAGE', 'BTL'),
        ('BRW021', 'Ruffino, Chianti, Docg12 Italy Red 750ML', 'BEVERAGE', 'BTL'),
        ('BRW022', 'Sababay Black Velvet Red', 'BEVERAGE', 'BTL'),
        ('BRW023', 'Sababay Ludisia Red', 'BEVERAGE', 'BTL'),
        ('BRW024', 'Sababay Pink Blossom Rose', 'BEVERAGE', 'BTL'),
        ('BRW025', 'Shiraz Carbenet De Bortoli 750ML', 'BEVERAGE', 'BTL'),
        ('BRW026', 'Tre Secoli Brachetto Dacqual Docg', 'BEVERAGE', 'BTL'),


